### ISSUE TITLE
Cannot compile with USE_QT=6: undefned references to BackendManager

### ISSUE THREAD

**Issue by michaellass** [pedrolcl/drumstick#12]
I'm struggling to compile this on Arch Linux against Qt6. As soon as I run cmake with `-DUSE_QT=6`, `make VERBOSE=1` fails with the following errors:

```
[ 38%] Linking CXX shared library libmp_svoxeas.so
cd /home/bevan/git/multiplatform-sonivoxeas/libsvoxeas && /usr/bin/cmake -E cmake_link_script CMakeFiles/mp_svoxeas.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC -shared -Wl,-soname,libmp_svoxeas.so.2 -o libmp_svoxeas.so.2.1.0 CMakeFiles/mp_svoxeas.dir/mp_svoxeas_autogen/mocs_compilation.cpp.o CMakeFiles/mp_svoxeas.dir/programsettings.cpp.o CMakeFiles/mp_svoxeas.dir/synthcontroller.cpp.o CMakeFiles/mp_svoxeas.dir/synthrenderer.cpp.o CMakeFiles/mp_svoxeas.dir/filewrapper.cpp.o  /usr/lib/libsonivox.so.3.6.12.0 /usr/lib/libQt6Multimedia.so.6.5.1 /usr/lib/libdrumstick-rt.so.2.7.2 /usr/lib/libQt6Gui.so.6.5.1 /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6Network.so.6.5.1 /usr/lib/libQt6Core.so.6.5.1 
/usr/bin/ld: CMakeFiles/mp_svoxeas.dir/synthrenderer.cpp.o: warning: relocation against `_ZN9drumstick2rt9MIDIInput10midiNoteOnEiii' in read-only section `.text'
/usr/bin/ld: CMakeFiles/mp_svoxeas.dir/synthrenderer.cpp.o: in function `SynthRenderer::SynthRenderer(QObject*)':
synthrenderer.cpp:(.text+0x6a): undefined reference to `drumstick::rt::BackendManager::BackendManager()'
/usr/bin/ld: synthrenderer.cpp:(.text+0x11b): undefined reference to `drumstick::rt::BackendManager::~BackendManager()'
/usr/bin/ld: CMakeFiles/mp_svoxeas.dir/synthrenderer.cpp.o: in function `SynthRenderer::~SynthRenderer()':
synthrenderer.cpp:(.text+0xccb): undefined reference to `drumstick::rt::BackendManager::~BackendManager()'
/usr/bin/ld: CMakeFiles/mp_svoxeas.dir/synthrenderer.cpp.o: in function `SynthRenderer::setMidiDriver(QString)':
synthrenderer.cpp:(.text+0x15ec): undefined reference to `drumstick::rt::BackendManager::inputBackendByName(QString)'
/usr/bin/ld: synthrenderer.cpp:(.text+0x162b): undefined reference to `drumstick::rt::MIDIInput::midiNoteOn(int, int, int)'
/usr/bin/ld: CMakeFiles/mp_svoxeas.dir/synthrenderer.cpp.o: relocation R_X86_64_PC32 against undefined protected symbol `_ZN9drumstick2rt9MIDIInput10midiNoteOnEiii' can not be used when making a shared object
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libsvoxeas/CMakeFiles/mp_svoxeas.dir/build.make:169: libsvoxeas/libmp_svoxeas.so.2.1.0] Error 1
```

Interestingly, version 2.0.0 with d2c95011c90ebacd168b74becf6c1ac83054f910 backported fails with the same error. In January, this built without problems on Arch. So I have a feeling that it could be related to the update to Qt 6.5.1. In January, this was still 6.4.1.

Do you have any idea what could cause this?

**Comment by pedrolcl** [comment]
I've moved this issue to the "drumstick" repository, which seems more appropriate than the old location

**Comment by pedrolcl** [comment]
Corresponding [ticket 49 in SourceForge](https://sourceforge.net/p/drumstick/bugs/49/)

**Comment by pedrolcl** [comment]
@antonio-rojas :

When configuring Qt6 with`FEATURE_no_direct_extern_access=ON`, like in your Arch package, I got this error:

    CMake Error at cmake/QtBuildInformation.cmake:508 (message):
      Feature "no_direct_extern_access": Forcing to "ON" breaks its condition:
    
          NOT WIN32 AND TEST_no_direct_extern_access
    
      Condition values dump:
    
          WIN32 = ""
          TEST_no_direct_extern_access = "FALSE"
    
    Call Stack (most recent call first):
      cmake/QtFeature.cmake:288 (qt_configure_add_report_error)
      cmake/QtFeature.cmake:410 (qt_feature_check_and_save_internal_value)
      cmake/QtFeature.cmake:625 (qt_evaluate_feature)
      cmake/QtBaseGlobalTargets.cmake:112 (qt_feature_module_end)
      CMakeLists.txt:130 (include)

So, I've needed to set TEST_no_direct_extern_access=TRUE as well in order to build Qt6 with the feature. This makes me think that it is considered an experimental feature and perhaps should be taken with some care, and not expose all users to it yet.

This has already disrupted several other projects:

* [plasma-nm](https://invent.kde.org/plasma/plasma-nm/-/merge_requests/247)
* [qutebrowser](https://github.com/qutebrowser/qutebrowser/issues/7624#issuecomment-1504768894)

**Comment by pedrolcl** [comment]
@dvzrv : an "official" fix is now in Git, branch "develop". It will be included in the next Drumstick release when it is ready.

**Comment by antonio-rojas** [comment]
> When configuring Qt6 with`FEATURE_no_direct_extern_access=ON`, like in your Arch package, I got this error

That means the feature test is failing on your system for some reason, it works fine here. The feature was turned on on Arch by recommendation from Qt's Thiago Maiceira himself.

**Comment by pedrolcl** [comment]
> That means the feature test is failing on your system for some reason, it works fine here. The feature was turned on on Arch by recommendation from Qt's Thiago Maiceira himself.

[I've noticed](https://bugreports.qt.io/browse/QTBUG-112332).

**Comment by pedrolcl** [comment]
Drumstick v2.8.0 has been released: https://sourceforge.net/projects/drumstick/files/2.8.0/

This issue is done on this release.
