### ISSUE TITLE
"Macro names must be identifiers" errors while building drumstick 2.8.0

### ISSUE THREAD

**Issue by GvMariani** [pedrolcl/drumstick#13]
While processing library/alsa stuff, new drumstick sources (2.8.0) fail to build here (gcc 11.2.0, x86_64), with multiple "macro names must be identifiers" errors (see attached full log of a failed build).
[BuildError.txt](https://github.com/pedrolcl/drumstick/files/12215959/BuildError.txt).

By looking at one failed command line, I noticed a definition looking suspect ("-D-DRTKIT_SUPPORT"): it looks like a spurious "-"...
Indeed, changing the line 26 in the CMakeLists.txt file for library/alsa from "$<$<BOOL:${HAVE_DBUS}>:-DRTKIT_SUPPORT>" to "$<$<BOOL:${HAVE_DBUS}>:DRTKIT_SUPPORT>" (ie removing the stray "-" before DRKIT_SUPPORT) it completely fixes the issue.

**Comment by pedrolcl** [comment]
What is your CMake version? The minimum supported CMake version is 3.14

The generated command line in the build log is wrong, but your solution is also wrong. You have enabled the option USE_DBUS, which also enables the macro "RTKIT_SUPPORT", which in turn enables using RealtimeKit.

If you take a look to the cmake 3.14 documentation (or newer),  [target_compile_definitions](https://cmake.org/cmake/help/v3.14/command/target_compile_definitions.html) says that:

> Any leading -D on an item will be removed. Empty items are ignored. For example, the following are all equivalent:

So, if your CMake is broken and doesn't do what it should do, then you should remove "-D" and not only the "-".

**Comment by pedrolcl** [comment]
Seems that this bug has already been detected in CMake:
https://gitlab.kitware.com/cmake/cmake/-/issues/24186

**Comment by GvMariani** [comment]
> What is your CMake version? The minimum supported CMake version is 3.14
> 

I have 3.21.3...

> The generated command line in the build log is wrong, but your solution is also wrong. You have enabled the option USE_DBUS, which also enables the macro "RTKIT_SUPPORT", which in turn enables using RealtimeKit.
> 
> If you take a look to the cmake 3.14 documentation (or newer), [target_compile_definitions](https://cmake.org/cmake/help/v3.14/command/target_compile_definitions.html) says that:
> > Any leading -D on an item will be removed. Empty items are ignored. For example, the following are all equivalent:
> 
> So, if your CMake is broken and doesn't do what it should do, then you should remove "-D" and not only the "-".

Oops...
You're right, I should remove also the "D": with my solution now I have "-DDRTKIT_SUPPORT" and this is plain wrong.
I will update my local patch and wait for a fixed release...

**Comment by pedrolcl** [comment]
Fix released in [v2.8.1](https://sourceforge.net/projects/drumstick/files/2.8.1/)
