### ISSUE TITLE
allow customizing of FluidSynth's reverb/chorus or use better defaults

### ISSUE THREAD

**Issue by mrbumpy409** [pedrolcl/drumstick#25]
It is no secret that FluidSynth's default reverb and chorus settings are not very good. The upcoming FluidSynth 2.4 will be [changing the defaults to much more pleasing settings](https://github.com/FluidSynth/fluidsynth/issues/1282). While we wait for FluidSynth 2.4, I would like to suggest either adding reverb & chorus customization options in the FluidSynth settings, and/or cherry-pick [this commit](https://github.com/FluidSynth/fluidsynth/commit/bd04f3f6c81a114f3ad52c8e29be3b44dccd010f) for a nice improvement to dmidiplayer's FluidSynth playback quality.

**Comment by pedrolcl** [comment]
This ticket belongs to the Drumstick::RT's fluidsynth plugin and configuration dialog. Once implemented, it will be used by [dmidiplayer](/pedrolcl/dmidiplayer), [VMPK](/pedrolcl/vmpk) and other applications.
